--- 
title: "Predictive Analytics Supplementary Notes"
date: "Last Updated: `r format(Sys.Date(), format='%B %d, %Y')`"
knit: "bookdown::render_book"
documentclass: krantz
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
fontsize: 12pt
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
site: bookdown::bookdown_site
description: "Supplementary notes to Daniel Linders's lectures on predictive analytics with insurance and actuarial science applications"
url: 'https\://daniellinders.github.io/predictive-analytics-supplementary-notes/'
github-repo: daniellinders/predictive-analytics-supplementary-notes
---

```{r setup, include=FALSE}
options(
  htmltools.dir.version = FALSE, 
  formatR.indent = 2,
  width = 55, 
  digits = 4, 
  warnPartialMatchAttr = FALSE, 
  warnPartialMatchDollar = FALSE
)

knitr::opts_chunk$set(
  echo = TRUE, 
  fig.align = "center"
)

# automatically create a bib database for R packages
knitr::write_bib(
  c(
    .packages(), 
    'bookdown', 
    'knitr', 
    'rmarkdown'
  ), 
  'packages.bib'
)
```

# Preface {-}



## Why read this book {-}



## Structure of the book {-}



## Software information and conventions {-}

The R session information when compiling this book is shown below:

```{r include=FALSE}
# only show versions of very relevant packages
sessionInfo <- function() {
  # uncomment this line if the following packages are installed 
  # lapply(c('shiny', 'miniUI'), loadNamespace)
  res = utils::sessionInfo()
  loaded = res$loadedOnly
  res$loadedOnly = loaded[intersect(names(loaded), c(
    # 'shiny', 'miniUI', 
    'bookdown', 'knitr', 'rmarkdown', 'htmltools', 'tools'
  ))]
  res$BLAS = res$LAPACK = NULL
  res
}
```

```{r}
sessionInfo()
```

## Acknowledgments {-}

